import Foundation

/// The one-tap "quick join" suggestion in the channels sheet: the
/// region-level geohash channel around the device region's main population
/// center. Derived from the device locale — no location access, no GPS; the
/// tap reuses the same path as typing the geohash and teleporting.
///
/// This replaced an earlier curated list of heavily censored countries. A
/// hand-picked roster invites disputes over who is on it and goes stale
/// with every political shift; deriving the suggestion from the locale
/// gives every country the same treatment under one rule.
///
/// Quick join is channel discovery, not protection: region cells are
/// public, well known, and trivially enumerable, so the suggested channel
/// must be assumed watched. Joining it hides nothing and bypasses nothing.
struct QuickJoinSuggestion {
    let regionCode: String
    let geohash: String

    /// Regional-indicator flag emoji derived from the ISO code.
    var flag: String {
        regionCode.unicodeScalars.reduce(into: "") { result, scalar in
            if let indicator = Unicode.Scalar(127397 + scalar.value) {
                result.unicodeScalars.append(indicator)
            }
        }
    }

    var localizedName: String {
        Locale.current.localizedString(forRegionCode: regionCode) ?? regionCode
    }

    /// The suggestion for the device's region, or nil when the region is
    /// unknown or unmapped (the section is hidden then).
    static func current(for locale: Locale = .current) -> QuickJoinSuggestion? {
        guard let code = locale.region?.identifier.uppercased(),
              let geohash = regionCells[code] else { return nil }
        return QuickJoinSuggestion(regionCode: code, geohash: geohash)
    }

    /// ISO 3166-1 alpha-2 region → the 2-character geohash cell over the
    /// country's main population center — the largest metro, not always the
    /// capital (US → New York, TR → Istanbul, MM → Yangon), because that is
    /// the cell where a country's channel actually forms. Someone elsewhere
    /// in the country lands in this cell too; the caption in the sheet says
    /// so rather than calling it "your country's channel".
    ///
    /// Coverage is every UN member state plus inhabited territories a
    /// device locale plausibly reports; a missing code just hides the row.
    /// Cells are 11.25° × 5.625°, so city-level coordinates are ample. The
    /// table is generated by geohashing each center's coordinates; the
    /// twelve entries the earlier roster shipped were independently
    /// verified in review and reproduce unchanged, and entries near a cell
    /// boundary were checked by hand. Distinct countries can legitimately
    /// share a cell (Seoul and Pyongyang are both "wy") — cells are big.
    private static let regionCells: [String: String] = [
        "AD": "sp", "AE": "th", "AF": "tw", "AG": "de",
        "AL": "sr", "AM": "sz", "AO": "kq", "AR": "69",
        "AT": "u2", "AU": "r3", "AW": "d6", "AZ": "tp",
        "BA": "sr", "BB": "dd", "BD": "wh", "BE": "u1",
        "BF": "ef", "BG": "sx", "BH": "th", "BI": "kx",
        "BJ": "s1", "BM": "dt", "BN": "w8", "BO": "6s",
        "BR": "6g", "BS": "dk", "BT": "tu", "BW": "ke",
        "BY": "u9", "BZ": "d5", "CA": "dp", "CD": "kr",
        "CF": "s2", "CG": "kr", "CH": "u0", "CI": "eb",
        "CL": "66", "CM": "s0", "CN": "wx", "CO": "d2",
        "CR": "d1", "CU": "dh", "CV": "e6", "CW": "d6",
        "CY": "sw", "CZ": "u2", "DE": "u3", "DJ": "sf",
        "DK": "u3", "DM": "dd", "DO": "d7", "DZ": "sn",
        "EC": "6p", "EE": "ud", "EG": "st", "ER": "sf",
        "ES": "ez", "ET": "sc", "FI": "ud", "FJ": "ru",
        "FM": "x9", "FO": "gg", "FR": "u0", "GA": "s0",
        "GB": "gc", "GD": "dd", "GE": "sz", "GF": "db",
        "GG": "gb", "GH": "eb", "GI": "ey", "GL": "fg",
        "GM": "ed", "GN": "e9", "GP": "dd", "GQ": "s0",
        "GR": "sw", "GT": "9f", "GU": "x4", "GW": "ed",
        "GY": "d9", "HK": "we", "HN": "d4", "HR": "u2",
        "HT": "d7", "HU": "u2", "ID": "qq", "IE": "gc",
        "IL": "sv", "IM": "gc", "IN": "tt", "IQ": "sv",
        "IR": "tn", "IS": "ge", "IT": "sr", "JE": "gb",
        "JM": "d7", "JO": "sv", "JP": "xn", "KE": "kz",
        "KG": "tx", "KH": "w6", "KI": "xb", "KM": "kv",
        "KN": "de", "KP": "wy", "KR": "wy", "KW": "tj",
        "KY": "d5", "KZ": "tx", "LA": "w7", "LB": "sy",
        "LC": "dd", "LI": "u0", "LK": "tc", "LR": "ec",
        "LS": "kd", "LT": "u9", "LU": "u0", "LV": "ud",
        "LY": "sm", "MA": "ev", "MC": "sp", "MD": "u8",
        "ME": "sr", "MG": "mh", "MH": "xc", "MK": "sr",
        "ML": "ef", "MM": "w4", "MN": "y2", "MO": "we",
        "MQ": "dd", "MR": "ee", "MT": "sq", "MU": "mk",
        "MV": "t8", "MW": "kv", "MX": "9g", "MY": "w2",
        "MZ": "ke", "NA": "k7", "NC": "rs", "NE": "s4",
        "NG": "s1", "NI": "d4", "NL": "u1", "NO": "u4",
        "NP": "tu", "NR": "rx", "NZ": "rc", "OM": "tk",
        "PA": "d1", "PE": "6m", "PF": "2s", "PG": "rq",
        "PH": "wd", "PK": "tk", "PL": "u3", "PR": "de",
        "PS": "sv", "PT": "ey", "PW": "wc", "PY": "6e",
        "QA": "th", "RE": "mh", "RO": "sx", "RS": "sr",
        "RU": "uc", "RW": "kx", "SA": "th", "SB": "rw",
        "SC": "mp", "SD": "sd", "SE": "u6", "SG": "w2",
        "SI": "u2", "SK": "u2", "SL": "e9", "SM": "sr",
        "SN": "ed", "SO": "t0", "SR": "dc", "SS": "s8",
        "ST": "s0", "SV": "d4", "SY": "sv", "SZ": "ke",
        "TD": "s6", "TG": "s1", "TH": "w4", "TJ": "tw",
        "TL": "qy", "TM": "tq", "TN": "sn", "TO": "2h",
        "TR": "sx", "TT": "d9", "TV": "ry", "TW": "ws",
        "TZ": "ky", "UA": "u8", "UG": "s8", "US": "dr",
        "UY": "6c", "UZ": "tx", "VA": "sr", "VC": "dd",
        "VE": "d9", "VI": "de", "VN": "w7", "VU": "rs",
        "WS": "2j", "XK": "sr", "YE": "sf", "YT": "mj",
        "ZA": "ke", "ZM": "kt", "ZW": "ks"
    ]
}
